CREATE TABLE group_purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    group_price NUMERIC(19, 2) NOT NULL,
    target_quantity INTEGER NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_group_purchases_product_variant
        FOREIGN KEY (product_variant_id) REFERENCES product_variants (id),
    CONSTRAINT ck_group_purchases_group_price CHECK (group_price > 0),
    CONSTRAINT ck_group_purchases_target_quantity CHECK (target_quantity > 0),
    CONSTRAINT ck_group_purchases_period CHECK (ends_at > starts_at),
    CONSTRAINT ck_group_purchases_status CHECK (status IN ('DRAFT', 'OPEN', 'CLOSED', 'CANCELLED'))
);

CREATE INDEX idx_group_purchases_product_variant_id ON group_purchases (product_variant_id);
CREATE INDEX idx_group_purchases_status_starts_at ON group_purchases (status, starts_at);
