CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_purchase_id BIGINT NOT NULL,
    buyer_id VARCHAR(100) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(19, 2) NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_group_purchase
        FOREIGN KEY (group_purchase_id) REFERENCES group_purchases (id),
    CONSTRAINT ck_orders_quantity CHECK (quantity > 0),
    CONSTRAINT ck_orders_unit_price CHECK (unit_price > 0),
    CONSTRAINT ck_orders_total_amount CHECK (total_amount > 0),
    CONSTRAINT ck_orders_status CHECK (status IN ('PLACED', 'CANCELLED'))
);

CREATE INDEX idx_orders_group_purchase_id ON orders (group_purchase_id);
CREATE INDEX idx_orders_buyer_id ON orders (buyer_id);
